### ISSUE TITLE
Consider using Electron instead 🙃

### ISSUE THREAD

**Issue by davidyuk** [aeternity/launcher#5]
- faster developing, reusing of existing web libraries
- easier to make a custom UI (to make it look fancy)
- easier to maintain cross-platform (Electron is a more high-level tool)
- require web developers that are easier to find than Erlang+GTK 
- possibility to reuse some stuff from blockchain explorer or even to combine projects

From the cons, of course:
- more resource consumption (RAM)
- bigger executable file (about 100mb?)

cc: @omar-saadoun @marc0olo

**Comment by nikita-fuchs** [comment]
Yes, please, as that would allow a broader range of members on the team to add adjustments and make the design fit to the current look and feel of the website and whatnot.

**Comment by zxq9** [comment]
The entire point of this is to be able to execute code from within the context of the node, natively, without a web stack in the way. This is not intended as a replacement or a competitor to any web tooling. Web tooling does not solve the problems that this is intended to solve, mainly the ability to easily build and launch nodes and run client-side code natively and directly within the context of a node.

Also, Electron is cancer.

**Comment by marc0olo** [comment]
Thanks for clarifying the purpose of this project, @zxq9 ! 🙏

**Comment by marc0olo** [comment]
We should generally try to avoid such confusion by providing respective background info in the README. There is lot of room for interpretation if somebody just reads the name of the repo.

**Comment by zxq9** [comment]
It would also be *awesome* if new ideas intended as QoL improvements for core development were not viewed immediately viewed as *threats* to the Interests of the Web. It is clear we need an entire world of web tooling to be able to function in the commercial space. It is also pretty obvious that web tooling is absolutely powerless to provide the kind of lower-level access to a node necessary to comfortably and quickly experiment with arbitrary features of a node from within the context of that node.

We need both!

**Comment by marc0olo** [comment]
Probably I shouldn't comment this now. Not sure what you are talking about.

But I am pretty confident that this issue wouldn't have been opened if this info existed in advance. The purpose was just not clear.

Independently of that, I absolutely agree.

**Comment by davidyuk** [comment]
> to execute code from within the context of the node

So, it is a kind of ide for node?

> web tooling is absolutely powerless to provide the kind of lower-level access

Can't you make some bridge to provide necessary access?

> to comfortably and quickly experiment with arbitrary features of a node

The GUI role doesn't seem to be well-defined.
